const { AddressLookup } = require("../models");

const addresses = [
  {
    postcode: "SK11AP",
    latitude: 53.4089152,
    longitude: -2.1520614,
    addresses: [
      {
        formatted_address: ["1 Silk Close", "", "", "Stockport", "Cheshire"],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "1",
        line_1: "1 Silk Close",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
      {
        formatted_address: ["2 Silk Close", "", "", "Stockport", "Cheshire"],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "2",
        line_1: "2 Silk Close",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
      {
        formatted_address: ["3 Silk Close", "", "", "Stockport", "Cheshire"],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "3",
        line_1: "3 Silk Close",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
      {
        formatted_address: ["4 Silk Close", "", "", "Stockport", "Cheshire"],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "4",
        line_1: "4 Silk Close",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
      {
        formatted_address: ["5 Silk Close", "", "", "Stockport", "Cheshire"],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "5",
        line_1: "5 Silk Close",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
      {
        formatted_address: ["6 Silk Close", "", "", "Stockport", "Cheshire"],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "6",
        line_1: "6 Silk Close",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
      {
        formatted_address: ["7 Silk Close", "", "", "Stockport", "Cheshire"],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "7",
        line_1: "7 Silk Close",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
      {
        formatted_address: ["8 Silk Close", "", "", "Stockport", "Cheshire"],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "8",
        line_1: "8 Silk Close",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
      {
        formatted_address: [
          "Maeto",
          "6 Silk Close",
          "",
          "Stockport",
          "Cheshire",
        ],
        thoroughfare: "Silk Close",
        building_name: "",
        sub_building_name: "Maeto",
        sub_building_number: "",
        building_number: "6",
        line_1: "Maeto",
        line_2: "6 Silk Close",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Stockport",
        county: "Cheshire",
        district: "Stockport",
        country: "England",
      },
    ],
  },
];

const seedAddressLookup = async () => {
  await AddressLookup.insertMany(addresses);
  console.log("[INFO]: Successfully seeded addressLookup");
};

module.exports = { seedAddressLookup };
