const { AddressLookup } = require("../models");

const addresses = [
  {
    postcode: "B12 9LP",
    latitude: 52.456569,
    longitude: -1.888122,
    addresses: [
      {
        formatted_address: [
          "49 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "49",
        line_1: "49 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "51 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "51",
        line_1: "51 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "53 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "53",
        line_1: "53 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "55 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "55",
        line_1: "55 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "57 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "57",
        line_1: "57 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "59 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "59",
        line_1: "59 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "61 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "61",
        line_1: "61 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "63 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "63",
        line_1: "63 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "65 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "65",
        line_1: "65 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "67 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "67",
        line_1: "67 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "69 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "69",
        line_1: "69 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "71 Edward Road",
          "",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "71",
        line_1: "71 Edward Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "A & Z Finances Ltd",
          "1 Edward Road",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "A & Z Finances Ltd",
        sub_building_number: "",
        building_number: "1",
        line_1: "A & Z Finances Ltd",
        line_2: "1 Edward Road",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Balsall Health Chemist",
          "1 Edward Road",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "Balsall Health Chemist",
        sub_building_number: "",
        building_number: "1",
        line_1: "Balsall Health Chemist",
        line_2: "1 Edward Road",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Pharmacy",
          "Balsall Heath Health Centre",
          "43 Edward Road",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "Balsall Heath Health Centre",
        sub_building_name: "Pharmacy",
        sub_building_number: "",
        building_number: "43",
        line_1: "Pharmacy",
        line_2: "Balsall Heath Health Centre",
        line_3: "43 Edward Road",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Southern Birmingham Community Health Nhs Trust",
          "Balsall Heath Health Centre",
          "43 Edward Road",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "Balsall Heath Health Centre",
        sub_building_name: "Southern Birmingham Community Health Nhs Trust",
        sub_building_number: "",
        building_number: "43",
        line_1: "Southern Birmingham Community Health Nhs Trust",
        line_2: "Balsall Heath Health Centre",
        line_3: "43 Edward Road",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Sure Health Ltd",
          "1 Edward Road",
          "",
          "Balsall Heath, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Edward Road",
        building_name: "",
        sub_building_name: "Sure Health Ltd",
        sub_building_number: "",
        building_number: "1",
        line_1: "Sure Health Ltd",
        line_2: "1 Edward Road",
        line_3: "",
        line_4: "",
        locality: "Balsall Heath",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
    ],
  },
  {
    postcode: "B29 5PZ",
    latitude: 52.436767578125,
    longitude: -1.9640045166015625,
    addresses: [
      {
        formatted_address: [
          "2 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "2",
        line_1: "2 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "26 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "26",
        line_1: "26 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "28 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "28",
        line_1: "28 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "30 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "30",
        line_1: "30 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "32 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "32",
        line_1: "32 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "34 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "34",
        line_1: "34 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "34a Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "34a",
        line_1: "34a Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "36 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "36",
        line_1: "36 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "4 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "4",
        line_1: "4 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "40 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "40",
        line_1: "40 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "42 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "42",
        line_1: "42 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "44 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "44",
        line_1: "44 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "6 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "6",
        line_1: "6 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "8 Weoley Castle Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "8",
        line_1: "8 Weoley Castle Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Flat 1",
          "38 Weoley Castle Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "Flat 1",
        sub_building_number: "1",
        building_number: "38",
        line_1: "Flat 1",
        line_2: "38 Weoley Castle Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Flat 2",
          "38 Weoley Castle Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Castle Road",
        building_name: "",
        sub_building_name: "Flat 2",
        sub_building_number: "2",
        building_number: "38",
        line_1: "Flat 2",
        line_2: "38 Weoley Castle Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
    ],
  },
  {
    postcode: "B29 4AA",
    latitude: 52.4359016418457,
    longitude: -1.9502519369125366,
    addresses: [
      {
        formatted_address: [
          "1 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "1",
        line_1: "1 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "11 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "11",
        line_1: "11 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "13 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "13",
        line_1: "13 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "15 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "15",
        line_1: "15 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "17 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "17",
        line_1: "17 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "19 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "19",
        line_1: "19 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "21 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "21",
        line_1: "21 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "23 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "23",
        line_1: "23 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "25 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "25",
        line_1: "25 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "27 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "27",
        line_1: "27 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "29 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "29",
        line_1: "29 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "31 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "31",
        line_1: "31 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "5 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "5",
        line_1: "5 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "7 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "7",
        line_1: "7 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "9 Weoley Hill",
          "",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "9",
        line_1: "9 Weoley Hill",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Polymer Express Consultancy Ltd",
          "17 Weoley Hill",
          "",
          "Selly Oak, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Weoley Hill",
        building_name: "",
        sub_building_name: "Polymer Express Consultancy Ltd",
        sub_building_number: "",
        building_number: "17",
        line_1: "Polymer Express Consultancy Ltd",
        line_2: "17 Weoley Hill",
        line_3: "",
        line_4: "",
        locality: "Selly Oak",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
    ],
  },
  {
    postcode: "B15 1TR",
    latitude: 52.472091,
    longitude: -1.918026,
    addresses: [
      {
        formatted_address: [
          "Cl Holistic Wellbeing Ltd",
          "Apex House",
          "3 Embassy Drive, Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Embassy Drive",
        sub_building_name: "Cl Holistic Wellbeing Ltd",
        sub_building_number: "",
        building_number: "3",
        line_1: "Cl Holistic Wellbeing Ltd",
        line_2: "Apex House",
        line_3: "3 Embassy Drive",
        line_4: "Calthorpe Road",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Clear Mind Business Solutions Ltd",
          "Apex House Calthorpe Road",
          "",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Apex House Calthorpe Road",
        building_name: "",
        sub_building_name: "Clear Mind Business Solutions Ltd",
        sub_building_number: "",
        building_number: "",
        line_1: "Clear Mind Business Solutions Ltd",
        line_2: "Apex House Calthorpe Road",
        line_3: "",
        line_4: "",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Enable Housing Ltd",
          "Apex House",
          "Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Apex House",
        sub_building_name: "Enable Housing Ltd",
        sub_building_number: "",
        building_number: "",
        line_1: "Enable Housing Ltd",
        line_2: "Apex House",
        line_3: "Calthorpe Road",
        line_4: "",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Greening Healthcare Ltd",
          "Apex House Calthorpe Road",
          "",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Apex House Calthorpe Road",
        building_name: "",
        sub_building_name: "Greening Healthcare Ltd",
        sub_building_number: "",
        building_number: "",
        line_1: "Greening Healthcare Ltd",
        line_2: "Apex House Calthorpe Road",
        line_3: "",
        line_4: "",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Hs Immigration Consultants Ltd",
          "Apex House Apex House",
          "Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Apex House Apex House",
        sub_building_name: "Hs Immigration Consultants Ltd",
        sub_building_number: "",
        building_number: "",
        line_1: "Hs Immigration Consultants Ltd",
        line_2: "Apex House Apex House",
        line_3: "Calthorpe Road",
        line_4: "",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Ka Empire Ltd",
          "3 First Floor Apex House Calthorpe Road",
          "",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "First Floor Apex House Calthorpe Road",
        building_name: "",
        sub_building_name: "Ka Empire Ltd",
        sub_building_number: "",
        building_number: "3",
        line_1: "Ka Empire Ltd",
        line_2: "3 First Floor Apex House Calthorpe Road",
        line_3: "",
        line_4: "",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "National Lottery Community Fund",
          "Apex House",
          "3 Embassy Drive, Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Embassy Drive",
        sub_building_name: "National Lottery Community Fund",
        sub_building_number: "",
        building_number: "3",
        line_1: "National Lottery Community Fund",
        line_2: "Apex House",
        line_3: "3 Embassy Drive",
        line_4: "Calthorpe Road",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Regus",
          "Apex House",
          "3 Embassy Drive, Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Embassy Drive",
        sub_building_name: "Regus",
        sub_building_number: "",
        building_number: "3",
        line_1: "Regus",
        line_2: "Apex House",
        line_3: "3 Embassy Drive",
        line_4: "Calthorpe Road",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Safeguard Financials Ltd",
          "Apex House",
          "3 Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Apex House",
        sub_building_name: "Safeguard Financials Ltd",
        sub_building_number: "",
        building_number: "3",
        line_1: "Safeguard Financials Ltd",
        line_2: "Apex House",
        line_3: "3 Calthorpe Road",
        line_4: "",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Spa Medica Eye Hospital",
          "Apex House",
          "3 Embassy Drive, Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Embassy Drive",
        sub_building_name: "Spa Medica Eye Hospital",
        sub_building_number: "",
        building_number: "3",
        line_1: "Spa Medica Eye Hospital",
        line_2: "Apex House",
        line_3: "3 Embassy Drive",
        line_4: "Calthorpe Road",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Spice Of Life (South West Midlands) Ltd",
          "Apex House Embassy Drive",
          "Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Apex House Embassy Drive",
        sub_building_name: "Spice Of Life (South West Midlands) Ltd",
        sub_building_number: "",
        building_number: "",
        line_1: "Spice Of Life (South West Midlands) Ltd",
        line_2: "Apex House Embassy Drive",
        line_3: "Calthorpe Road",
        line_4: "",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Stepping Stones Care (Midlands) Ltd",
          "Apex House",
          "3 Embassy Drive, Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Embassy Drive",
        sub_building_name: "Stepping Stones Care (Midlands) Ltd",
        sub_building_number: "",
        building_number: "3",
        line_1: "Stepping Stones Care (Midlands) Ltd",
        line_2: "Apex House",
        line_3: "3 Embassy Drive",
        line_4: "Calthorpe Road",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Tax Whizz Ltd",
          "Apex House",
          "3 Embassy Drive, Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Embassy Drive",
        sub_building_name: "Tax Whizz Ltd",
        sub_building_number: "",
        building_number: "3",
        line_1: "Tax Whizz Ltd",
        line_2: "Apex House",
        line_3: "3 Embassy Drive",
        line_4: "Calthorpe Road",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Timhy Services Ltd",
          "Apex House",
          "Calthorpe Road",
          "Edgbaston, Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Calthorpe Road",
        building_name: "Apex House",
        sub_building_name: "Timhy Services Ltd",
        sub_building_number: "",
        building_number: "",
        line_1: "Timhy Services Ltd",
        line_2: "Apex House",
        line_3: "Calthorpe Road",
        line_4: "",
        locality: "Edgbaston",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
    ],
  },
  {
    postcode: "B8 1NH",
    latitude: 52.48964669999999,
    longitude: -1.8536902,
    addresses: [
      {
        formatted_address: [
          "137 Alum Rock Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "137",
        line_1: "137 Alum Rock Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "147a Alum Rock Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "147a",
        line_1: "147a Alum Rock Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "155 Alum Rock Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "155",
        line_1: "155 Alum Rock Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "157 Alum Rock Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "157",
        line_1: "157 Alum Rock Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "159 Alum Rock Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "159",
        line_1: "159 Alum Rock Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "160 Alum Rock Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "160",
        line_1: "160 Alum Rock Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "161 Alum Rock Road",
          "",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "",
        sub_building_number: "",
        building_number: "161",
        line_1: "161 Alum Rock Road",
        line_2: "",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Al-Mu'min Delights Ltd",
          "131-133 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Al-Mu'min Delights Ltd",
        sub_building_number: "",
        building_number: "131-133",
        line_1: "Al-Mu'min Delights Ltd",
        line_2: "131-133 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Basharats",
          "139-141 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Basharats",
        sub_building_number: "",
        building_number: "139-141",
        line_1: "Basharats",
        line_2: "139-141 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Dixy Chicken",
          "163 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Dixy Chicken",
        sub_building_number: "",
        building_number: "163",
        line_1: "Dixy Chicken",
        line_2: "163 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Fastfood Republic Ltd",
          "163 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Fastfood Republic Ltd",
        sub_building_number: "",
        building_number: "163",
        line_1: "Fastfood Republic Ltd",
        line_2: "163 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Imran's Dresses",
          "143 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Imran's Dresses",
        sub_building_number: "",
        building_number: "143",
        line_1: "Imran's Dresses",
        line_2: "143 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Madani Gift Store",
          "135 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Madani Gift Store",
        sub_building_number: "",
        building_number: "135",
        line_1: "Madani Gift Store",
        line_2: "135 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Onkar Eye Care Opticians",
          "151 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Onkar Eye Care Opticians",
        sub_building_number: "",
        building_number: "151",
        line_1: "Onkar Eye Care Opticians",
        line_2: "151 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Rivaaj Birmingham Ltd",
          "137 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Rivaaj Birmingham Ltd",
        sub_building_number: "",
        building_number: "137",
        line_1: "Rivaaj Birmingham Ltd",
        line_2: "137 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Royal Restaurant",
          "131-133 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Royal Restaurant",
        sub_building_number: "",
        building_number: "131-133",
        line_1: "Royal Restaurant",
        line_2: "131-133 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Smart Wear",
          "147-149 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Smart Wear",
        sub_building_number: "",
        building_number: "147-149",
        line_1: "Smart Wear",
        line_2: "147-149 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Smart Wear Fashions Ltd",
          "147-149 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Smart Wear Fashions Ltd",
        sub_building_number: "",
        building_number: "147-149",
        line_1: "Smart Wear Fashions Ltd",
        line_2: "147-149 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Zainab Fashions",
          "145 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Zainab Fashions",
        sub_building_number: "",
        building_number: "145",
        line_1: "Zainab Fashions",
        line_2: "145 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
      {
        formatted_address: [
          "Zewar",
          "153 Alum Rock Road",
          "",
          "Birmingham",
          "West Midlands",
        ],
        thoroughfare: "Alum Rock Road",
        building_name: "",
        sub_building_name: "Zewar",
        sub_building_number: "",
        building_number: "153",
        line_1: "Zewar",
        line_2: "153 Alum Rock Road",
        line_3: "",
        line_4: "",
        locality: "",
        town_or_city: "Birmingham",
        county: "West Midlands",
        district: "Birmingham",
        country: "England",
      },
    ],
  },
];

const seedAddressLookup = async () => {
  await AddressLookup.insertMany(addresses);
  console.log("[INFO]: Successfully seeded addressLookup");
};

module.exports = { seedAddressLookup };
